config/routes.rb
Rails.application.routes.draw do
  #get '/', to: 'home#index' #Classe(Controller) e Metodo(Action)
  root to: 'home#index'

  resources :study_items, only: [:show, :new, :create, :edit, :update, :destroy] do
    patch 'mark_as_done', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :study_items
end

app/models/study_item.rb
class StudyItem < ApplicationRecord
    belongs_to :category
    validates :title, presence: true

    def full_title
        "#{title} - #{category.title}"
    end

    def status!
        update(status: true)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        #código, acessar db, etc
        #render 'index'
        @study_items = StudyItem.all()
    end
end

app/controllers/study_items_controller.rb
class StudyItemsController < ApplicationController
    
    def new
        @study_item = StudyItem.new
    end

    def show 
        id = params[:id]
        @study_item = StudyItem.find(id)
    end

    def create
        @study_item = StudyItem.new(study_item_params)

        if @study_item.save
            flash[:notice] = 'Novo item de estudo adicionado'
            redirect_to root_path
        else
            flash[:alert] = 'Não foi possivel adicionar o item de estudo'
            render "new"
        end
    end

    def edit
        set_study_item
    end

    def update
        set_study_item
        if @study_item.update(study_item_params)
            redirect_to @study_item
        else
            render :edit
        end
    end

    def mark_as_done
        set_study_item
        @study_item.status!
        redirect_to @study_item
    end

    def destroy
        set_study_item
        @study_item.destroy
        redirect_to root_path
    end

    private

    def set_study_item
        @study_item = StudyItem.find(params[:id])
    end

    def study_item_params
        params.require(:study_item).permit(:title, :category_id, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<footer>
  Projeto realizado durante o iugu for devs
</footer>

app/views/home/index.html.erb
<ul> 
    <% @study_items.each do |si| %>
        <li> 
         <%= link_to(si.full_title, study_item_path(si.id)) %> 
        </li>
    <% end %>
</ul>

<%= link_to 'Cadastrar Novo Item', new_study_item_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diário de Estudos - iugu for Devs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <div class='container'>
    <% if alert %>
    <div class='alert alert-warning'>
      <% alert %>
      </div>
      <% end %>
    <% if notice %>
    <div class='alert alert-info'>
      <% notice %>
      </div>
      <% end %>
    <%= yield %>
    </div>
    <%= render 'footer' %>
  </body>
</html>

app/views/shared/_nav.html.erb
<h1>Diário de Estudos - iugu for devs</h1>
<nav>
<ul>
  <li><%= link_to 'Início', root_path %></li>
</ul>
</nav>

app/views/study_items/_form.html.erb
<% study_item.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
  <%= form_with(model: study_item) do |f| %>
    <div>
      <%= f.label :title, 'Título' %>
      <%= f.text_field :title, required: "required"  %>
    </div>
    <div>
      <%= f.label :category_id, 'Categoria' %>
      <%= f.collection_select :category_id, Category.all, :id, :title %>
    </div>
    <div>
      <span>Feito?</span>
      <%= f.label :status, 'Sim' %>
      <%= f.radio_button :stauts, 'true' %>
      <%= f.label :status, 'Não' %>
      <%= f.radio_button :status, 'false' %>
    </div>
  
    <%= f.submit %>
  <% end %>

app/views/study_items/edit.html.erb
<h1>Editar Item de Estudo</h1>

<%= render partial: 'form', locals: { study_item: @study_item } %>

app/views/study_items/new.html.erb
<h1>Cadastrar Item de Estudo</h1>

<%= render partial: 'form', locals: { study_item: @study_item } %>

app/views/study_items/show.html.erb
<%= @study_item.title %>
<%= link_to 'Editar', edit_study_item_path(@study_item) %>

<%= link_to 'Apagar', study_item_path(@study_item), method: :delete, data: {confirm: 'Quer apagar esta tarefa?'} %>

<% if @study_item.status? %>
  Feito
<% else %>
  <%= button_to 'Marcar como feito', mark_as_done_study_item_path(@study_item), method: :patch %>
<% end %>